### ISSUE TITLE
NumberFormatException in log - backoff time?

### ISSUE THREAD

**Issue by Zomis** [Zomis/Duga#137]
```WARN net.zomis.duga.chat.StackExchangeChatBot - Error in drainMessagesQueue: java.lang.NumberFormatException: For input string: "1 second."
java.lang.NumberFormatException: For input string: "1 second."
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_25]
        at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_25]
        at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_25]
        at net.zomis.duga.chat.StackExchangeChatBot.postMessageToChat(StackExchangeChatBot.java:188) [duga-core-0.1.jar:na]
        at net.zomis.duga.chat.StackExchangeChatBot.attemptPostMessageToChat(StackExchangeChatBot.java:105) [duga-core-0.1.jar:na]
        at net.zomis.duga.chat.StackExchangeChatBot.lambda$postDrainedMessages$6(StackExchangeChatBot.java:283) [duga-core-0.1.jar:na]
        at net.zomis.duga.chat.StackExchangeChatBot$$Lambda$32/1257811880.accept(Unknown Source) ~[na:na]
        at java.util.ArrayList.forEach(ArrayList.java:1249) ~[na:1.8.0_25]
        at net.zomis.duga.chat.StackExchangeChatBot.postDrainedMessages(StackExchangeChatBot.java:277) [duga-core-0.1.jar:na]
        at net.zomis.duga.chat.StackExchangeChatBot.drainMessagesQueue(StackExchangeChatBot.java:227) [duga-core-0.1.jar:na]
        at net.zomis.duga.chat.StackExchangeChatBot.lambda$start$0(StackExchangeChatBot.java:61) [duga-core-0.1.jar:na]
        at net.zomis.duga.chat.StackExchangeChatBot$$Lambda$9/1630183983.run(Unknown Source) [duga-core-0.1.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_25]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]```

**Comment by Zomis** [comment]
This seems to cause issues with the comments detection.
