### ISSUE TITLE
Problem when having too many webapps running at once

### ISSUE THREAD

**Issue by Zomis** [Zomis/Duga#88]
At the moment I have disabled Cardshifter and Minesweeper Flags Statistics because when all three webapps are running at once, it creates an out of memory error on the server directly on startup.

It didn't use to do this before I switched to Grails (although it did run out of memory sometimes, see #60).

Running Duga alone does not seem to be problematic.

From system.out:

    INFO org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler - Initializing ExecutorService  'executor'
    INFO org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext - Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@770cb1c9: startup date [Thu Jun 18 19:24:54 CEST 2015]; root of context hierarchy
    Jun 18, 2015 7:30:48 PM org.apache.catalina.startup.HostConfig deployWARs
    SEVERE: Error waiting for multi-thread deployment of WAR files to complete
    java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)

**Comment by Zomis** [comment]
`setenv.sh`:

    CATALINA_OPTS="-Xms512m -Xmx2048m"

I cannot explain why Tomcat didn't seem to use the environment variables that were set but... this seems to work, for now....

http://chat.stackexchange.com/transcript/message/22603893#22603893

**Comment by Zomis** [comment]
This has been fixed now, will see whether or not it has fixed #60 as well.
